services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    # keep container running
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      # anonymous mount to prevent being overwritten
      # when mounting ./app with no node_modules
      - /app/node_modules
