version: "3.8"
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    # keep container running
    stdin_open: true
    env_file:
      - .env
    ports:
      - 3000:${PORT}
    volumes:
      - ./app:/app
      # anonymous volume to prevent being overwritten
      # when mounting ./app with no node_modules
      - /app/node_modules
